version: 2

orbs:
  python: circleci/python@0.2.1

jobs:
  test_and_publish_model:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/project/disaster_messaging_classification_model
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install pip
          command: pip install --upgrade pip
      - run:
          name: Install poetry
          command: pip install poetry
      - run:
          name: Install poetry packages
          command: make poetry-install
      - run:
          name: Set script permissions and fetch data
          command: make fetch-dataset
      - run:
          name: preprocess the data
          command: make process-data
      - run:
          name: Train model
          command: make train-model
      - run:
          name: Run model test
          command: make test-model
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create and upload packages
          command: make package

  test_and_build_app:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/project/disaster_messaging_app
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install pip
          command: pip install --upgrade pip
      - run:
          name: Install poetry
          command: pip install poetry
      - run:
          name: Install poetry packages
          command: make poetry-install
      - run:
          name: Install nltk resources
          command: make nltk-resources
      - run:
          name: Run API tests with Python 3.7
          command: make test-app

  build_and_push_to_heroku_docker:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/project/disaster_messaging_app
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Setup Heroku CLI
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Build and Push Image
          command: |
            make build-app-heroku push-app-heroku
      - run:
          name: Release to Heroku
          command: |
            heroku container:release web --app $HEROKU_APP_NAME

workflows:
  version: 2
  build-app-workflow:
    jobs:
      - test_and_publish_model:
          filters:
            branches:
              only:
                - master
      - test_and_build_app:
          requires:
            - test_and_publish_model
          filters:
            branches:
              only:
                - master
      - build_and_push_to_heroku_docker:
          requires:
            - test_and_build_app
          filters:
            branches:
              only:
                - master
